### ISSUE TITLE
Unable to compile on ubuntu.

### ISSUE THREAD

**Issue by jamie-pate** [akozadaev/dwm-statusbar#3]
It seems like the LFLAGS isn't quite in the correct spot for newer gcc? 

```
gcc -Wall -std=c99 -pedantic -O3 -c statusbar.c
gcc -lX11 -o statusbar statusbar.o
statusbar.o: In function `set_status':
statusbar.c:(.text+0x25): undefined reference to `XStoreName'
statusbar.o: In function `close_display':
statusbar.c:(.text+0x4c): undefined reference to `XCloseDisplay'
statusbar.o: In function `set_status':
statusbar.c:(.text+0x37): undefined reference to `XSync'
statusbar.o: In function `main':
statusbar.c:(.text.startup+0x92): undefined reference to `XOpenDisplay'
statusbar.c:(.text.startup+0x3be): undefined reference to `XStoreName'
statusbar.c:(.text.startup+0x3cc): undefined reference to `XSync'
collect2: error: ld returned 1 exit status
Makefile:62: recipe for target 'statusbar' failed
make: *** [statusbar] Error 1
```
This seems to fix the issue:
```
diff --git a/Makefile b/Makefile
index 08945c8..7354c99 100644
--- a/Makefile
+++ b/Makefile
@@ -59,7 +59,7 @@ install: release
        @echo "DONE"
 
 ${TARGET}: build_host.h ${OBJ}
-       ${CC} ${LFLAGS} -o $@ ${OBJ}
+       ${CC} -o $@ ${OBJ} ${LFLAGS}
 
 %.o: %.c
        ${CC} ${CFLAGS} -c $?
```

**Comment by akozadaev** [comment]
Interesting. Which version of gcc have you got? Certainly does compile properly on my system (both gcc & clang).
Sounds like a very pointless (and breaking) change in gcc if it proves to be for real.

**Comment by akozadaev** [comment]
hmm... looks like that is correct. What a silly requirement. Oh well... fixed anyway.
Thanks for reporting.

**Comment by jamie-pate** [comment]
For reference: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html says:
"It makes a difference where in the command you write this option; the
linker searches and processes libraries and object files in the order they
are specified. Thus, ‘foo.o -lz bar.o’ searches library ‘z’ after
file foo.o but before bar.o. If bar.o refers to functions in ‘z’, those
functions may not be loaded"

**Comment by akozadaev** [comment]
Cool, thanks for the info. It makes sense but will probably break a lot of stuff anyway like in this case.
